# Copyright (c) 2020 Famedly GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later

default:
  image: registry.fedoraproject.org/fedora-minimal:latest

stages:
  - build
  - test
  - trigger

build:lib:
  stage: build
  tags:
    - docker
  script:
    - microdnf --assumeyes --nodocs install cmake gcc gcc-c++
    - cmake . -Bbuild
    - cmake --build build
  artifacts:
    paths:
      - build/

test:lib:
  stage: test
  tags:
    - docker
  needs:
    - build:lib
  script:
    - microdnf --assumeyes --nodocs install cmake
    - pushd build/tests
    - ctest .
  artifacts:
    paths:
      - build/tests/Testing/Temporary/

trigger:javascript:
  stage: trigger
  trigger:
    strategy: depend
    include: javascript/.gitlab-ci.yml

build_win32:
  tags:
    - docker
    - famedly
  image: ubuntu:bionic
  stage: build
  script:
    - apt update
    - apt install -y curl gnupg2 software-properties-common
    - curl https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg | apt-key add -
    - add-apt-repository 'deb https://pkg.mxe.cc/repos/apt bionic main'
    - apt update
    - apt install -y mxe-i686-w64-mingw32.static-gcc mxe-i686-w64-mingw32.static-cmake
    - ln -sf /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-gcc /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-g++ /usr/lib/mxe/usr/x86_64-pc-linux-gnu/bin # https://github.com/mxe/mxe/issues/2449
    - export PATH=$PATH:/usr/lib/mxe/usr/bin
    - sed -i 's/\(library(olm\)\b/\1 SHARED/' CMakeLists.txt
    - useradd -m build
    - chown -R 'build:' '.'
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && i686-w64-mingw32.static-cmake .' build
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && i686-w64-mingw32.static-cmake --build .' build
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && i686-w64-mingw32.static-strip libolm.dll' build
  artifacts:
    paths:
      - libolm.dll

build_win64:
  tags:
    - docker
    - famedly
  image: ubuntu:bionic
  stage: build
  script:
    - apt update
    - apt install -y curl gnupg2 software-properties-common
    - curl https://pkg.mxe.cc/repos/apt/client-conf/mxeapt.gpg | apt-key add -
    - add-apt-repository 'deb https://pkg.mxe.cc/repos/apt bionic main'
    - apt update
    - apt install -y mxe-x86-64-w64-mingw32.static-gcc mxe-x86-64-w64-mingw32.static-cmake
    - ln -sf /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-gcc /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-g++ /usr/lib/mxe/usr/x86_64-pc-linux-gnu/bin # https://github.com/mxe/mxe/issues/2449
    - sed -i 's/\(library(olm\)\b/\1 SHARED/' CMakeLists.txt
    - useradd -m build
    - chown -R 'build:' '.'
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && x86_64-w64-mingw32.static-cmake .' build
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && x86_64-w64-mingw32.static-cmake --build .' build
    - su -c 'export PATH=$PATH:/usr/lib/mxe/usr/bin && x86_64-w64-mingw32.static-strip libolm.dll' build
  artifacts:
    paths:
      - libolm.dll
