default:
  image: docker.io/emscripten/emsdk:latest

stages:
  - build
  - test

build:js:
  stage: build
  script:
    - ln -sf $(which python3) /usr/local/bin/python
    - make js
  artifacts:
    paths:
      - javascript/olm.js
      - javascript/olm.wasm
      - javascript/olm_legacy.js

test:js:
  stage: test
  needs:
    - build:js
  script:
    - pushd javascript
    - npm i
    - npm run test
