name: "All the sdk specific jobs"

on:
  workflow_call:

jobs:
  pub-dev-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@7b1734b5b08d53fbf347cf96b664fa1a49cc6497
      - name: Prepare publish
        run: ./package_flutter.sh
      - name: pub.dev publish dry run
        working-directory: publishing/flutter
        run: |
          dart pub get
          dart pub publish --dry-run
